StripeApiTask/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('items.urls')),
]

items/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('item/<int:id>/',views.item_details,name='item_details'),
    path('order/',views.create_checkout_session),
    path('buy/<int:id>/',views.create_payment_session),
    path('success/',views.success,name='success'),
]

items/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=50,decimal_places=2)
    currency = models.CharField(max_length=20,
    choices=(('usd','$'),('rub','₽')),default='usd'
    )

    def __str__(self) -> str:
        return self.name


class Discount(models.Model):
    value = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    type = models.CharField(max_length=10,choices=(
        ('percentage','Persentage'),('fixed','Fixed amount')),default='percentage')

class Tax(models.Model):
    value = models.DecimalField(max_digits=10,decimal_places=2,default=0)



class Order(models.Model):
    tax = models.ForeignKey(Tax,on_delete=models.SET_NULL,blank=True,null=True)
    discount = models.ForeignKey(Discount,on_delete=models.SET_NULL,blank=True,null=True)
    def get_total(self):
        total_items_sum = sum([item.get_total_price() for item in self.items.all()])
        if self.discount.type == 'percentage':
            total_price = total_items_sum*(1-self.discount.value/100)
        else:
            total_price = total_items_sum-self.discount.value
        return total_price+self.tax
        
class OrderItem(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE,related_name='items')
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def get_total_price(self):
        return self.item.price*self.quantity

items/views.py
from django.shortcuts import render,get_object_or_404
from .models import Item,Order,OrderItem,Discount,Tax
from django.conf import settings
from django.http import JsonResponse
from django.conf import settings
import json,stripe
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
stripe.api_key = settings.STRIPE_SECRET_KEY


STRIPE_PUBLIC_KEY = settings.STRIPE_PUBLISHABLE_KEY
# Create your views here.

def index(request):
    items = Item.objects.all()
    context = {
        'items':items,
        'stripe_key':STRIPE_PUBLIC_KEY,
    }
    return render(request,'items/index.html',context)

def item_details(request,id):
    item = Item.objects.get(pk=id)
    context = {
        'item':item,
        'stripe_key':STRIPE_PUBLIC_KEY,
    }
    return render(request,'items/details.html',context)


def get_currency_course(currency):
    course = {
        'usd':1,
        'rub':0.014
    }
    return course.get(currency,1)


def get_success_url(request):
    url = request.build_absolute_uri(reverse('success'))
    return url
def get_cancel_url(request,id):
    url = request.build_absolute_uri(reverse('item_details',args=[id]))
    return url
@csrf_exempt
def create_checkout_session(request):
    if request.method =='POST':
        body = request.body
        data = json.loads(body)
        orders = data.get('orders',[])
        line_items = []
        
        for order in orders:
            item = get_object_or_404(Item,id=order['id'])
            product = stripe.Product.create(name=item.name)
            price = stripe.Price.create(
                unit_amount=int(float(item.price)*100*get_currency_course(item.currency)),
                currency='usd',
                product=product,
            )
            line_items.append(
                {
                    'price':price,
                    'quantity': order['quantity'],
                }
            )
        session = stripe.checkout.Session.create(
            line_items=line_items,
            mode='payment',
            success_url=get_success_url(request),
            cancel_url=get_cancel_url(request,item.pk),
            )
        return JsonResponse({'session':session})
    


def create_payment_session(request,id):
    item = Item.objects.get(pk=id)
    product = stripe.Product.create(name=item.name)
    price = stripe.Price.create(
    unit_amount=int(item.price*100),
    currency=item.currency,
    product=product.stripe_id,
    )
    session = stripe.checkout.Session.create(
    line_items=[{
        'price': price,
        'quantity':1
    }],
    mode='payment',
    success_url=get_success_url(request),
    cancel_url=get_cancel_url(request,item.pk),
    )
    return JsonResponse({'session':session})

def success(request):
    return render(request,'items/success.html')

items/templates/items/details.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Buy {{ item.name }}</title>
        <script src="https://js.stripe.com/v3/"></script>
    </head>
    <body>
        <h1>{{Item.name}}</h1>
        <p>{{ item.description }}</p>
        <p>{{ item.price }}</p>
        <button id="buy-button">Buy</button>
        <script type="text/javascript">
            var stripe = Stripe('{{stripe_key}}');
            var buyButton = document.getElementById('buy-button');
            buyButton.addEventListener('click', function() {
                fetch('/buy/{{item.id}}', {method: 'GET'})
                .then(response => {return response.json()})
                .then(session => {
                    stripe.redirectToCheckout({ sessionId: session.session.id });
                })
                .catch( error => {console.error();})
      });
    </script>
    </body>
</html>

items/templates/items/index.html
<!DOCTYPE html>
{% load static %} 
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Homepage</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://js.stripe.com/v3/"></script>  
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                    </ul>
                    <div class="d-flex">
                        <button class="btn btn-outline-dark" id="buy-btn">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart-total">0</span>
                        </button>
                    </div>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Shop in style</h1>
                    <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for item in items %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{item.name}}</h5>
                                    <!-- Product price-->
                                    {{item.get_currency_display}}{{item.price}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-outline-dark mt-auto" href="{% url 'item_details' item.pk %}">View Details</a>
                                    <button class="btn btn-outline-dark mt-auto add-to-cart" data-item="{{item.id}}">Add</button> 
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <h2>There is no items yet</h2>
                    {% endfor %}
                    
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        
        <script>

        cartTotal = document.getElementById('cart-total');
        console.log(cartTotal);
        let addCartBtns = document.getElementsByClassName('add-to-cart');
        let orderItems = [];
        let orderItem;
        let orderedProducts = {};
        var orders = [];
        var stripe = Stripe('{{stripe_key}}');


        for (let i = 0; i < addCartBtns.length; i++) {
            orderItem = {
                "id": parseInt(addCartBtns[i].dataset.item),
                "quantity": 0,
            };
            orderItems.push(orderItem)
        }
        for (let i = 0; i < addCartBtns.length; i++) {
            addCartBtns[i].addEventListener('click', function () {
                cartTotal.innerText = parseInt(cartTotal.innerText) + 1;
                orderedProducts[i] = 1;
                orderItems[i].quantity = orderItems[i].quantity + 1;
            })
        }
        let buyBtn = document.getElementById("buy-btn");
        buyBtn.addEventListener('click', function () {
            for (key in orderedProducts) {
                orders.push(orderItems[key]);
            }
            let data = {
                'orders': orders
            }
            console.log(data);






            fetch('/order/', {
                method: "POST",
                headers: {
                    // 'X-CSRFToken':'{{ csrf_token }}',
                    'Content_Type': 'application/json',
                },
                body: JSON.stringify(data),
            })
                .then(response => { return response.json() })
                .then(session => {
                    console.log('Success:', session);
                    stripe.redirectToCheckout({ sessionId: session.session.id });
                })
                .catch((error) => {
                    console.error('Error:', error);

                });

        })


        </script>
    </body>
</html>

items/templates/items/success.html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Success</h1> 
        <p>We received your purchase request;<br/> we'll be in touch shortly!</p>
      </div>
    </body>
</html>